/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package possystem;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;

/**
 *
 * @author tylar
 */
public class LoginPanel extends CustomPanel {

    /**
     * Creates new form LoginPanel
     */
    private final MainFrame mainFrame;
    
    //buttongroup ensures only one button clicked at a time
    private ButtonGroup bg;
    
    //just to add clear and delete button convieniently
    private final String[] buttonOrder = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "Clear", "0", "Delete"};
    
    //login page
    public LoginPanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        this.bg = new ButtonGroup();
        //sets top left clock field
        setClockField(ClockLabel);
        
        //just centers added fields 
        TopPanel.setLayout(new FlowLayout(FlowLayout.CENTER));
        MiddlePanel.setLayout(new FlowLayout(FlowLayout.CENTER));
        BottomPanel.setLayout(new FlowLayout(FlowLayout.CENTER));
        
        //bolder clocklabel border for this page
        ClockLabel.setBorder(BorderFactory.createLineBorder(Color.black, 2));
        //4x3 grid for 12 buttons 
        GridLayout layout = new GridLayout(4, 3);
        //removes padding
        layout.setVgap(0);
        layout.setHgap(0);
        
        //adds 12 buttons to keypad
        KeyPad.setLayout(layout);
        
        //loop to actually initialize and add buttons to panel
        for(int x=0; x<12; x++){
            CustomButton button = new CustomButton(buttonOrder[x], this);
            //bg = buttongroup -- ensures only 1 button clicked at a time
            bg.add(button);
            KeyPad.add(button);
            
        }
        
    }
    
    //called from keypad buttons to update pin displayed (should probably not be displayed in final product)
    public void numberClicked(String string){
        PinField.setText(PinField.getText() + string);
    }
    
    //called from keypad 'Delete' button to backspace the current entered pin
    public void deleteEntry(){
        PinField.setText(PinField.getText().substring(0, PinField.getText().length()-1));
    }
    
    //called from keypad 'clear' button to clear entry
    public void clearEntry(){
        PinField.setText("");
    }
    
    //self explanatory
    public ButtonGroup getButtonGroup(){
        return this.bg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClockLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        MiddlePanel = new javax.swing.JPanel();
        KeyPad = new javax.swing.JPanel();
        BottomPanel = new javax.swing.JPanel();
        EnterButton = new javax.swing.JToggleButton();
        TopPanel = new javax.swing.JPanel();
        PinField = new javax.swing.JTextField();
        ErrorLabel = new javax.swing.JLabel();

        ClockLabel.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        ClockLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ClockLabel.setText("jTextField1");
        ClockLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClockLabelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please Enter Your Pin");

        KeyPad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        KeyPad.setPreferredSize(new java.awt.Dimension(400, 550));

        javax.swing.GroupLayout KeyPadLayout = new javax.swing.GroupLayout(KeyPad);
        KeyPad.setLayout(KeyPadLayout);
        KeyPadLayout.setHorizontalGroup(
            KeyPadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        KeyPadLayout.setVerticalGroup(
            KeyPadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MiddlePanelLayout = new javax.swing.GroupLayout(MiddlePanel);
        MiddlePanel.setLayout(MiddlePanelLayout);
        MiddlePanelLayout.setHorizontalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(KeyPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MiddlePanelLayout.setVerticalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KeyPad, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        EnterButton.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        EnterButton.setText("Enter");
        EnterButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        EnterButton.setPreferredSize(new java.awt.Dimension(600, 50));
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BottomPanelLayout = new javax.swing.GroupLayout(BottomPanel);
        BottomPanel.setLayout(BottomPanelLayout);
        BottomPanelLayout.setHorizontalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EnterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BottomPanelLayout.setVerticalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PinField.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        PinField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PinField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PinField.setPreferredSize(new java.awt.Dimension(450, 50));

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(PinField, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PinField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        ErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorLabel)
                .addGap(34, 34, 34)
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(MiddlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClockLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClockLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClockLabelActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        try {
            //call mainframe.LogIn() to check pin validity
            //pass it the current PinField text, converted into in integer
            if(mainFrame.logIn(Integer.parseInt(PinField.getText()))){
                mainFrame.setNewPanel(new MainMenuPanel(mainFrame), Boolean.FALSE, this);
            }
            //if LogIn() returns false, invalid pin
            else{
                ErrorLabel.setText("*Invalid pin please try again*");
                PinField.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EnterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JTextField ClockLabel;
    private javax.swing.JToggleButton EnterButton;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JPanel KeyPad;
    private javax.swing.JPanel MiddlePanel;
    private javax.swing.JTextField PinField;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
