/*
 * Here comes the text of your license
 * Each line should be prefixed with  *
 */
package possystem;

import java.awt.event.ActionEvent;
import possystem.menuitems.MenuItem;
import possystem.menuitems.MenuSubCategory;

/**
 *
 * @author dakingofcheckerz
 */
public class MenuSubCategoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuSubCategoryPanel
     */
    public MenuSubCategoryPanel(MenuSubCategory subCategory) {
        super();
        initComponents();

        this.SubCategoryLabel.setText(subCategory.getName());

        for (MenuItem menuItem : subCategory.getMenuItemsArray()) {
            MenuItemButton button = new MenuItemButton(menuItem);
            button.addActionListener(evt -> {
                MenuItemButtonActionPerformed(evt);
            });

            this.SubCategoryButtonsPanel.add(button);
        }
    }

    public void MenuItemButtonActionPerformed(ActionEvent evt) {
        MenuItemButton button = (MenuItemButton) evt.getSource();

        button.getMenuItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubCategoryLabel = new javax.swing.JLabel();
        SubCategoryButtonsPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        SubCategoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubCategoryLabel.setText("SubCategory Name");
        add(SubCategoryLabel, java.awt.BorderLayout.PAGE_START);

        SubCategoryButtonsPanel.setLayout(new java.awt.GridLayout(4, 2, 12, 12));
        add(SubCategoryButtonsPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubCategoryButtonsPanel;
    private javax.swing.JLabel SubCategoryLabel;
    // End of variables declaration//GEN-END:variables
}
