package possystem;

import possystem.menuitems.MenuItem;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.BorderFactory;
import possystem.menuitems.MenuItemOption;
import possystem.menuitems.OrderedMenuItem;
import possystem.menuitems.Topping;

/**
 *
 * @author glenn
 */
public class MenuItemDetailsPanel extends CustomPanel {

    //item for the details being displayed
    private final MenuItem menuItem;
    
    //complete order for display
    private final CustomerOrder customerOrder;
    
    //mainframe for new panel calls
    private final MainFrame mainFrame;
    
    //lists for visual elements
    private List<MenuItemOptionPanel> optionPanels;
    private List<ToppingPanel> toppingPanels;

    public MenuItemDetailsPanel(MainFrame mainFrame, MenuItem menuItem, CustomerOrder customerOrder) {
        initComponents();
        this.menuItem = menuItem;
        this.customerOrder = customerOrder;
        this.mainFrame = mainFrame;
        initialize();
    }

    //various ui updating calls
    private void initialize() {
        this.optionPanels = new ArrayList();
        this.toppingPanels = new ArrayList();

        CurrentItemLabel.setText(menuItem.getName());
        BasePriceLabel.setText(String.format("$%.2f", menuItem.getBasePrice()));
        this.ExtraCommentsArea.setText(menuItem.getComments());

        initializeOptions();
        initializeToppings();
        updateAddItemButton();
    }

    //display all the large options for current item
    private void initializeOptions() {
        List<MenuItemOption> options = menuItem.getOptions();

        if (options.size() > 0) {
            MenuItemOptionsPanel.remove(NoOptionsLabel);

            for (int i = 0; i < options.size(); i++) {
                MenuItemOption option = options.get(i);

                MenuItemOptionPanel newPanel = new MenuItemOptionPanel(option, i, option.getDefaultValue());
                this.MenuItemOptionsPanel.add(newPanel);
                this.optionPanels.add(newPanel);

                ArrayList<OptionValueToggleButton> buttons = newPanel.getButtons();

                buttons.forEach(button -> {
                    button.setBorder(BorderFactory.createLineBorder(Color.black, 2));
                    button.addActionListener(evt -> {
                        onOptionStatusChange(evt);
                    });
                });
            }
        }
    }

    public void onOptionStatusChange(ActionEvent evt) {
        updateAddItemButton();
    }

    private void initializeToppings() {
        List<UUID> toppingIds = this.menuItem.getPossibleToppings();

        for (var toppingId : toppingIds) {
            MenuItem topping = this.mainFrame.getToppingMenu().getMenuItem(toppingId);
            ToppingPanel newPanel = new ToppingPanel(topping);
            this.ToppingsPanel.add(newPanel);

            this.toppingPanels.add(newPanel);
        }
    }

    private void updateAddItemButton() {
        if (this.optionPanels.isEmpty()) {
            return;
        }

        boolean shouldEnableButton = true;

        for (MenuItemOptionPanel optionPanel : optionPanels) {
            if (optionPanel.getOption().isRequired() && !optionPanel.isSelected()) {
                shouldEnableButton = false;
                break;
            }
        }

        this.AddItemButton.setEnabled(shouldEnableButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CurrentItemPanel = new javax.swing.JPanel();
        CurrentItemTextLabel = new javax.swing.JLabel();
        CurrentItemLabel = new javax.swing.JLabel();
        BasePriceTextLabel = new javax.swing.JLabel();
        BasePriceLabel = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        AddItemButton = new javax.swing.JButton();
        CommentsPanel = new javax.swing.JPanel();
        CommentsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ExtraCommentsArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        MenuItemOptionsPanel = new javax.swing.JPanel();
        NoOptionsLabel = new javax.swing.JLabel();
        ToppingsPanel = new javax.swing.JPanel();

        CurrentItemPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                CurrentItemPanelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        CurrentItemTextLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CurrentItemTextLabel.setText("Current Item:");

        CurrentItemLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CurrentItemLabel.setText("jLabel3");

        BasePriceTextLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BasePriceTextLabel.setText("Base Price:");

        BasePriceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BasePriceLabel.setText("jLabel3");

        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CurrentItemPanelLayout = new javax.swing.GroupLayout(CurrentItemPanel);
        CurrentItemPanel.setLayout(CurrentItemPanelLayout);
        CurrentItemPanelLayout.setHorizontalGroup(
            CurrentItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentItemPanelLayout.createSequentialGroup()
                .addGroup(CurrentItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CurrentItemPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(CurrentItemTextLabel)
                        .addGap(6, 6, 6)
                        .addComponent(CurrentItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CurrentItemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BasePriceTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BasePriceLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CurrentItemPanelLayout.setVerticalGroup(
            CurrentItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentItemPanelLayout.createSequentialGroup()
                .addGroup(CurrentItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CurrentItemPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(CurrentItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentItemTextLabel)
                            .addComponent(CurrentItemLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CurrentItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BasePriceTextLabel)
                            .addComponent(BasePriceLabel)))
                    .addGroup(CurrentItemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        AddItemButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddItemButton.setText("Add Item");
        AddItemButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        AddItemButton.setEnabled(false);
        AddItemButton.setMaximumSize(new java.awt.Dimension(66, 66));
        AddItemButton.setMinimumSize(new java.awt.Dimension(66, 66));
        AddItemButton.setPreferredSize(new java.awt.Dimension(66, 66));
        AddItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemButtonActionPerformed(evt);
            }
        });

        CommentsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CommentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CommentsLabel.setText("Extra Comments");

        ExtraCommentsArea.setEditable(false);
        ExtraCommentsArea.setColumns(20);
        ExtraCommentsArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ExtraCommentsArea.setLineWrap(true);
        ExtraCommentsArea.setRows(5);
        ExtraCommentsArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ExtraCommentsArea);

        javax.swing.GroupLayout CommentsPanelLayout = new javax.swing.GroupLayout(CommentsPanel);
        CommentsPanel.setLayout(CommentsPanelLayout);
        CommentsPanelLayout.setHorizontalGroup(
            CommentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CommentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CommentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(CommentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        CommentsPanelLayout.setVerticalGroup(
            CommentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommentsPanelLayout.createSequentialGroup()
                .addComponent(CommentsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        MenuItemOptionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        MenuItemOptionsPanel.setLayout(new java.awt.GridLayout(0, 1, 12, 12));

        NoOptionsLabel.setFont(NoOptionsLabel.getFont().deriveFont((NoOptionsLabel.getFont().getStyle() | java.awt.Font.ITALIC)));
        NoOptionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoOptionsLabel.setText("No Options");
        NoOptionsLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        NoOptionsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuItemOptionsPanel.add(NoOptionsLabel);

        jPanel1.add(MenuItemOptionsPanel);

        ToppingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Toppings"));
        ToppingsPanel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ToppingsPanel.setMinimumSize(new java.awt.Dimension(132, 22));
        ToppingsPanel.setLayout(new java.awt.GridLayout(1, 0, 12, 12));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToppingsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CommentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(CurrentItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CurrentItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CommentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToppingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemButtonActionPerformed

        ArrayList<Topping> toppings = new ArrayList();
        ArrayList<Integer> options = new ArrayList();

        for (ToppingPanel toppingPanel : this.toppingPanels) {
            Topping topping = toppingPanel.getTopping();
            int count = toppingPanel.getCount();

            if (count == 0) {
                continue;
            }

            topping.setCount(count);
            toppings.add(topping);
        }

        for (var optionPanel : optionPanels) {
            options.add(optionPanel.getSelectedValueIndex());
        }

        customerOrder.addMenuItem(new OrderedMenuItem(this.menuItem, toppings, options));
        mainFrame.setNewPanel(new NewOrderPanel(mainFrame, customerOrder));
    }//GEN-LAST:event_AddItemButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        mainFrame.setNewPanel(new NewOrderPanel(mainFrame, customerOrder));
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void CurrentItemPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_CurrentItemPanelAncestorAdded
        // TODO add your hanasdfsadfas
    }//GEN-LAST:event_CurrentItemPanelAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemButton;
    private javax.swing.JLabel BasePriceLabel;
    private javax.swing.JLabel BasePriceTextLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CommentsLabel;
    private javax.swing.JPanel CommentsPanel;
    private javax.swing.JLabel CurrentItemLabel;
    private javax.swing.JPanel CurrentItemPanel;
    private javax.swing.JLabel CurrentItemTextLabel;
    private javax.swing.JTextArea ExtraCommentsArea;
    private javax.swing.JPanel MenuItemOptionsPanel;
    private javax.swing.JLabel NoOptionsLabel;
    private javax.swing.JPanel ToppingsPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
