/*
 * Here comes the text of your license
 * Each line should be prefixed with  *
 */
package possystem;

import java.util.ArrayList;
import java.util.List;
import possystem.menuitems.MenuItemOption;
import possystem.menuitems.MenuItemOptionValue;

/**
 *
 * @author dakingofcheckerz
 */
public class MenuItemOptionPanel extends javax.swing.JPanel {

    private MenuItemOption option;
    private int index; // Index of option in MenuItem option List

    /**
     * Creates new form MenuItemOptionPanel
     */
    public MenuItemOptionPanel(MenuItemOption option, int index) {
        initComponents();

        this.option = option;
        this.index = index;

        initialize();
    }

    private void initialize() {
        OptionTitleLabel.setText(option.getName() + ':');

        initializeOptionButtons();
    }

    private void initializeOptionButtons() {
        List<MenuItemOptionValue> values = option.getPossibleValues();

        for (int i = 0; i < values.size(); i++) {
            MenuItemOptionValue value = values.get(i);

            OptionValueToggleButton button = new OptionValueToggleButton(value, i);

            this.add(button);
            this.OptionButtonGroup.add(button);
            button.setSize(69, 69);
        }
    }

    public int getSelectedIndex() {
        return ((OptionValueToggleButton) OptionButtonGroup.getSelection()).getIndex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionButtonGroup = new javax.swing.ButtonGroup();
        OptionTitleLabel = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        OptionTitleLabel.setText("Option Title:");
        add(OptionTitleLabel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup OptionButtonGroup;
    private javax.swing.JLabel OptionTitleLabel;
    // End of variables declaration//GEN-END:variables
}
