/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package possystem;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;

/**
 *
 * @author tylar
 */
public class NewOrderPanel extends CustomPanel {

    private final MainFrame mainFrame;
    private final CustomerOrder customerOrder;

    public NewOrderPanel(MainFrame mainFrame, CustomerOrder customerOrder) {
        initComponents();
        this.OrderDetailsTextArea.setFont(new Font(Font.MONOSPACED,
                this.getFont().getStyle(),
                this.getFont().getSize()));

        setClockField(ClockLabel);
        this.customerOrder = customerOrder;
        this.mainFrame = mainFrame;
        OrderIDLabel.setText(customerOrder.getOrderID().toString());
        CustomerNameLabel.setText(customerOrder.getCustomerName());
        CustomerPhoneLabel.setText(customerOrder.getCustomerPhoneNumber());
        CustomerOrderTotalLabel.setText(String.format("%.2f", customerOrder.getOrderTotal()));

        if (!customerOrder.isDelivery()) {
            AddressLabel.setText("Pickup");
            CustomerAddressLabel.setVisible(false);
        } else {
            CustomerAddressLabel.setText(customerOrder.getCustomerAddress());
        }
        
        

        OrderDetailsTextArea.setText(customerOrder.toString());

        setupMenuCategories();
    }

    private void setupMenuCategories() {
        for (String categoryName : this.mainFrame.getMenu().getMenuCategoryNames()) {
            JButton button = new JButton(categoryName);
            button.setBorder(BorderFactory.createLineBorder(Color.black, 2));
            button.addActionListener(evt -> {
                MenuCategoryButtonActionPerformed(evt);
            });

            this.MenuCategoriesPanel.add(button);
        }
    }

    private void MenuCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JButton button = (JButton) evt.getSource();
        String categoryName = button.getText();

        mainFrame.setNewPanel(new MenuCategoryPanel(mainFrame, customerOrder, categoryName), true, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuCategoriesPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        CurrentOrderLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        ClockLabel = new javax.swing.JTextField();
        OrderIDLabel = new javax.swing.JLabel();
        CancelOrderButton = new javax.swing.JButton();
        OrderInfoPanel = new javax.swing.JPanel();
        TicketTextArea = new javax.swing.JScrollPane();
        OrderDetailsTextArea = new javax.swing.JTextArea();
        NameLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        OrderTotalLabel = new javax.swing.JLabel();
        EditInfoButton = new javax.swing.JButton();
        CustomerNameLabel = new javax.swing.JLabel();
        CustomerPhoneLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        CustomerAddressLabel = new javax.swing.JLabel();
        CustomerOrderTotalLabel = new javax.swing.JLabel();
        PlaceOrderButton = new javax.swing.JButton();

        MenuCategoriesPanel.setLayout(new java.awt.GridLayout(5, 2, 12, 12));

        CurrentOrderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CurrentOrderLabel.setText("Current Order:");

        UsernameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsernameLabel.setText("User's Name");

        ClockLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClockLabel.setText("jTextField1");
        ClockLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClockLabelActionPerformed(evt);
            }
        });

        OrderIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OrderIDLabel.setText("jLabel6");

        CancelOrderButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelOrderButton.setText("Cancel Order");
        CancelOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CancelOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderPanelLayout.createSequentialGroup()
                        .addComponent(ClockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CurrentOrderLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addGap(68, 68, 68)
                .addComponent(CancelOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentOrderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrderIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CancelOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        OrderDetailsTextArea.setEditable(false);
        OrderDetailsTextArea.setColumns(20);
        OrderDetailsTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OrderDetailsTextArea.setRows(5);
        OrderDetailsTextArea.setText("order items & prices");
        OrderDetailsTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TicketTextArea.setViewportView(OrderDetailsTextArea);

        NameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NameLabel.setText("Name:");

        PhoneNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PhoneNumberLabel.setText("Phone Number:");

        OrderTotalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrderTotalLabel.setText("Order Total:  $");

        EditInfoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditInfoButton.setText("Change Customer Info");
        EditInfoButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        EditInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditInfoButtonActionPerformed(evt);
            }
        });

        CustomerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CustomerNameLabel.setText("jLabel7");

        CustomerPhoneLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CustomerPhoneLabel.setText("jLabel8");

        AddressLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddressLabel.setText("Address:");

        CustomerAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CustomerAddressLabel.setText("jLabel10");

        CustomerOrderTotalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CustomerOrderTotalLabel.setText("jLabel11");

        PlaceOrderButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PlaceOrderButton.setText("Place Order");
        PlaceOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PlaceOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderInfoPanelLayout = new javax.swing.GroupLayout(OrderInfoPanel);
        OrderInfoPanel.setLayout(OrderInfoPanelLayout);
        OrderInfoPanelLayout.setHorizontalGroup(
            OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlaceOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                        .addComponent(NameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                        .addComponent(PhoneNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(CustomerAddressLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditInfoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                        .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                                .addComponent(OrderTotalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustomerOrderTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AddressLabel))
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addComponent(TicketTextArea))
                .addContainerGap())
        );
        OrderInfoPanelLayout.setVerticalGroup(
            OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(CustomerNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLabel)
                    .addComponent(CustomerPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TicketTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerOrderTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PlaceOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuCategoriesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OrderInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(MenuCategoriesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditInfoButtonActionPerformed
        try {
            mainFrame.setNewPanel(new CustomerInfoPanel(mainFrame, customerOrder), true, this);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(NewOrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EditInfoButtonActionPerformed

    private void CancelOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelOrderButtonActionPerformed
        try {
            mainFrame.setNewPanel(new MainMenuPanel(mainFrame), false, this);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(NewOrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainFrame.clearLastPanel();
    }//GEN-LAST:event_CancelOrderButtonActionPerformed

    private void PlaceOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceOrderButtonActionPerformed
        try {
            mainFrame.setNewPanel(new MainMenuPanel(mainFrame), false, this);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(NewOrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainFrame.removeCustomerOrder(customerOrder.getOrderID().toString());
        try {
            mainFrame.addCustomerOrder(customerOrder);
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_PlaceOrderButtonActionPerformed

    private void ClockLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClockLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClockLabelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JButton CancelOrderButton;
    private javax.swing.JTextField ClockLabel;
    private javax.swing.JLabel CurrentOrderLabel;
    private javax.swing.JLabel CustomerAddressLabel;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JLabel CustomerOrderTotalLabel;
    private javax.swing.JLabel CustomerPhoneLabel;
    private javax.swing.JButton EditInfoButton;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel MenuCategoriesPanel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextArea OrderDetailsTextArea;
    private javax.swing.JLabel OrderIDLabel;
    private javax.swing.JPanel OrderInfoPanel;
    private javax.swing.JLabel OrderTotalLabel;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JButton PlaceOrderButton;
    private javax.swing.JScrollPane TicketTextArea;
    private javax.swing.JLabel UsernameLabel;
    // End of variables declaration//GEN-END:variables
}
