/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package possystem;

import java.text.DecimalFormat;

/**
 *
 * @author tylar
 */
public class NewOrderPanel extends CustomPanel {

    private MainFrame mainFrame;
    private CustomerOrder customerOrder;
    private DecimalFormat df;
    
    public NewOrderPanel(MainFrame mainFrame, CustomerOrder customerOrder) {
        initComponents();
        setClockField(ClockLabel);
        this.customerOrder = customerOrder;
        this.mainFrame = mainFrame;
        OrderIDLabel.setText(customerOrder.getOrderID().toString());
        CustomerNameLabel.setText(customerOrder.getCustomerName());
        CustomerPhoneLabel.setText(customerOrder.getCustomerPhoneNumber());
        CustomerOrderTotalLabel.setText(String.format("%.2f",customerOrder.getOrderTotal()));
        
        if(customerOrder.getCustomerAddress() != null){
            CustomerAddressLabel.setText(customerOrder.getCustomerAddress());
        }
        else{
            AddressLabel.setVisible(false);
            CustomerAddressLabel.setVisible(false);
        }
        
        jTextArea1.setText(customerOrder.toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TicketTextArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CurrentOrderLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        OrderTotalLabel = new javax.swing.JLabel();
        DrinksButton = new javax.swing.JButton();
        EntreesButton = new javax.swing.JButton();
        AppetizersButton = new javax.swing.JButton();
        MerchButton = new javax.swing.JButton();
        EditInfoButton = new javax.swing.JButton();
        DessertsButton = new javax.swing.JButton();
        UsernameLabel = new javax.swing.JLabel();
        ClockLabel = new javax.swing.JTextField();
        OrderIDLabel = new javax.swing.JLabel();
        CustomerNameLabel = new javax.swing.JLabel();
        CustomerPhoneLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        CustomerAddressLabel = new javax.swing.JLabel();
        CustomerOrderTotalLabel = new javax.swing.JLabel();
        CancelOrderButton = new javax.swing.JButton();
        PlaceOrderButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("order items & prices");
        TicketTextArea.setViewportView(jTextArea1);

        CurrentOrderLabel.setText("Current Order:");

        NameLabel.setText("Name:");

        PhoneNumberLabel.setText("Phone Number:");

        OrderTotalLabel.setText("Order Total:  $");

        DrinksButton.setText("Drinks");
        DrinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinksButtonActionPerformed(evt);
            }
        });

        EntreesButton.setText("Entree's");
        EntreesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreesButtonActionPerformed(evt);
            }
        });

        AppetizersButton.setText("Appetizers");
        AppetizersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppetizersButtonActionPerformed(evt);
            }
        });

        MerchButton.setText("Restaurant merch?");
        MerchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MerchButtonActionPerformed(evt);
            }
        });

        EditInfoButton.setText("Change Customer Info");
        EditInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditInfoButtonActionPerformed(evt);
            }
        });

        DessertsButton.setText("Desserts");
        DessertsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertsButtonActionPerformed(evt);
            }
        });

        UsernameLabel.setText("User's Name");

        ClockLabel.setText("jTextField1");

        OrderIDLabel.setText("jLabel6");

        CustomerNameLabel.setText("jLabel7");

        CustomerPhoneLabel.setText("jLabel8");

        AddressLabel.setText("Address:");

        CustomerAddressLabel.setText("jLabel10");

        CustomerOrderTotalLabel.setText("jLabel11");

        CancelOrderButton.setText("Cancel Order");
        CancelOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelOrderButtonActionPerformed(evt);
            }
        });

        PlaceOrderButton.setText("Place Order");
        PlaceOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ClockLabel)
                            .addComponent(UsernameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EntreesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addComponent(DrinksButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AppetizersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(CurrentOrderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OrderIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(CancelOrderButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MerchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DessertsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TicketTextArea, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustomerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PhoneNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustomerPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(CustomerAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OrderTotalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustomerOrderTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddressLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(PlaceOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(ClockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentOrderLabel)
                            .addComponent(OrderIDLabel)
                            .addComponent(CancelOrderButton))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TicketTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerOrderTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlaceOrderButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NameLabel)
                                    .addComponent(CustomerNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PhoneNumberLabel)
                                    .addComponent(CustomerPhoneLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CustomerAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(265, 265, 265))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DrinksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DessertsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AppetizersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MerchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EntreesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DrinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinksButtonActionPerformed
        mainFrame.setNewPanel(new DrinksPanel(mainFrame, customerOrder), true, this);
    }//GEN-LAST:event_DrinksButtonActionPerformed

    private void EntreesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntreesButtonActionPerformed

    private void AppetizersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppetizersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppetizersButtonActionPerformed

    private void MerchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MerchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MerchButtonActionPerformed

    private void EditInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditInfoButtonActionPerformed
        mainFrame.setNewPanel(new CustomerInfoPanel(mainFrame, customerOrder), true, this);
    }//GEN-LAST:event_EditInfoButtonActionPerformed

    private void DessertsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertsButtonActionPerformed
        
    }//GEN-LAST:event_DessertsButtonActionPerformed

    private void CancelOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelOrderButtonActionPerformed
        mainFrame.setNewPanel(new MainMenuPanel(mainFrame), false, this);
        mainFrame.clearLastPanel();
    }//GEN-LAST:event_CancelOrderButtonActionPerformed

    private void PlaceOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceOrderButtonActionPerformed
        mainFrame.setNewPanel(new MainMenuPanel(mainFrame), false, this);
        mainFrame.removeCustomerOrder(customerOrder.getOrderID().toString());
        mainFrame.addCustomerOrder(customerOrder);
    }//GEN-LAST:event_PlaceOrderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JButton AppetizersButton;
    private javax.swing.JButton CancelOrderButton;
    private javax.swing.JTextField ClockLabel;
    private javax.swing.JLabel CurrentOrderLabel;
    private javax.swing.JLabel CustomerAddressLabel;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JLabel CustomerOrderTotalLabel;
    private javax.swing.JLabel CustomerPhoneLabel;
    private javax.swing.JButton DessertsButton;
    private javax.swing.JButton DrinksButton;
    private javax.swing.JButton EditInfoButton;
    private javax.swing.JButton EntreesButton;
    private javax.swing.JButton MerchButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel OrderIDLabel;
    private javax.swing.JLabel OrderTotalLabel;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JButton PlaceOrderButton;
    private javax.swing.JScrollPane TicketTextArea;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
