/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package possystem;

import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tylar
 */
public class OrderHistoryPanel extends CustomPanel {

    private MainFrame mainFrame;
    private ArrayList<CustomerOrder> customerOrders;
    private int selectedOrderIndex;

    public OrderHistoryPanel(MainFrame mainFrame) throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        this.mainFrame = mainFrame;
        this.customerOrders = mainFrame.getCustomerOrders();
        this.selectedOrderIndex = 0;

        // Use a monospace font for text boxes for proper formatting
        Font monospacedFont = new Font(Font.MONOSPACED, this.getFont().getStyle(),
                this.getFont().getSize());

        OrderHistoryTextArea.setFont(monospacedFont);
        SelectedOrderTextArea.setFont(monospacedFont);

        displayOrders();
    }

    private void displayOrders() {
        for (int i = 0; i < customerOrders.size(); i++) {
            OrderHistoryTextArea.setText(OrderHistoryTextArea.getText()
                    + customerOrders.get(i).toString() + "\n\n\n");
        }

        if (!customerOrders.isEmpty()) {
            SelectedOrderTextArea.setText(customerOrders.get(selectedOrderIndex).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        SelectedOrderLabel = new javax.swing.JLabel();
        OrderIDInput = new javax.swing.JTextField();
        SearchByIDButton = new javax.swing.JButton();
        OrLabel = new javax.swing.JLabel();
        PreviousOrderButton = new javax.swing.JButton();
        NextOrderButton = new javax.swing.JButton();
        SelectedOrderPane = new javax.swing.JScrollPane();
        SelectedOrderTextArea = new javax.swing.JTextArea();
        EditOrderButton = new javax.swing.JButton();
        OrdersLogLabel = new javax.swing.JLabel();
        OrderHistoryPanel = new javax.swing.JScrollPane();
        OrderHistoryTextArea = new javax.swing.JTextArea();
        BackButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SelectedOrderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SelectedOrderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectedOrderLabel.setText("Selected Order");

        OrderIDInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrderIDInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        OrderIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderIDInputActionPerformed(evt);
            }
        });

        SearchByIDButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SearchByIDButton.setText("Search by ID");
        SearchByIDButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SearchByIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByIDButtonActionPerformed(evt);
            }
        });

        OrLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrLabel.setText("OR");

        PreviousOrderButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PreviousOrderButton.setText("Previous Order");
        PreviousOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PreviousOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousOrderButtonActionPerformed(evt);
            }
        });

        NextOrderButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NextOrderButton.setText("NextOrder");
        NextOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NextOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextOrderButtonActionPerformed(evt);
            }
        });

        SelectedOrderTextArea.setColumns(20);
        SelectedOrderTextArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SelectedOrderTextArea.setRows(5);
        SelectedOrderTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SelectedOrderPane.setViewportView(SelectedOrderTextArea);

        EditOrderButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditOrderButton.setText("Edit Order");
        EditOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        EditOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditOrderButtonActionPerformed(evt);
            }
        });

        OrdersLogLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrdersLogLabel.setText("Orders Log");

        OrderHistoryPanel.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        OrderHistoryTextArea.setColumns(20);
        OrderHistoryTextArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrderHistoryTextArea.setRows(5);
        OrderHistoryPanel.setViewportView(OrderHistoryTextArea);

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EditOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SelectedOrderPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PreviousOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(NextOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(OrLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchByIDButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OrderIDInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectedOrderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(OrdersLogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(OrderHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)))
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectedOrderLabel)
                    .addComponent(OrdersLogLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OrderIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchByIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OrLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PreviousOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(NextOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectedOrderPane, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OrderHistoryPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        try {
            mainFrame.setNewPanel(new MainMenuPanel(mainFrame), Boolean.FALSE, this);
        } catch (IOException ex) {
            Logger.getLogger(OrderHistoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderHistoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BackButtonActionPerformed

    private void PreviousOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousOrderButtonActionPerformed
        if (selectedOrderIndex > 0) {
            selectedOrderIndex--;
            SelectedOrderTextArea.setText(customerOrders.get(selectedOrderIndex).toString());
        }
    }//GEN-LAST:event_PreviousOrderButtonActionPerformed

    private void OrderIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderIDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderIDInputActionPerformed

    private void NextOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextOrderButtonActionPerformed
        if (selectedOrderIndex < customerOrders.size() - 1) {
            selectedOrderIndex++;
            SelectedOrderTextArea.setText(customerOrders.get(selectedOrderIndex).toString());
        }
    }//GEN-LAST:event_NextOrderButtonActionPerformed

    private void EditOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOrderButtonActionPerformed
        mainFrame.setNewPanel(new NewOrderPanel(mainFrame, customerOrders.get(selectedOrderIndex)), Boolean.FALSE, this);
    }//GEN-LAST:event_EditOrderButtonActionPerformed

    private void SearchByIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByIDButtonActionPerformed
        String orderID = OrderIDInput.getText();

        for (int i = 0; i < customerOrders.size(); i++) {
            if (customerOrders.get(i).getOrderID().toString().equals(orderID)) {
                SelectedOrderTextArea.setText(customerOrders.get(i).toString());
                selectedOrderIndex = i;
                return;
            }
        }
    }//GEN-LAST:event_SearchByIDButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton EditOrderButton;
    private javax.swing.JButton NextOrderButton;
    private javax.swing.JLabel OrLabel;
    private javax.swing.JScrollPane OrderHistoryPanel;
    private javax.swing.JTextArea OrderHistoryTextArea;
    private javax.swing.JTextField OrderIDInput;
    private javax.swing.JLabel OrdersLogLabel;
    private javax.swing.JButton PreviousOrderButton;
    private javax.swing.JButton SearchByIDButton;
    private javax.swing.JLabel SelectedOrderLabel;
    private javax.swing.JScrollPane SelectedOrderPane;
    private javax.swing.JTextArea SelectedOrderTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
