/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package possystem;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.border.Border;


/**
 *
 * @author tylar
 */
public class SchedulingPanel extends CustomPanel {

    private MainFrame mainFrame;
    private String[] months = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
    private int currentMonth, currentDay, currentYear, firstDay;
    private Calendar calendar;
    private SchedulingCalendar schedulingCalendar;
    
    public SchedulingPanel(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        setClockField(ClockLabel);
        createCalendar();
        YearLabel.setText("" + currentYear);
        MonthLabel.setText(months[currentMonth]);
    }

    private void createCalendar(){
        
        int height = (int) mainFrame.getHeight()-235;
        int width = (int) mainFrame.getWidth()-39;

        calendar = Calendar.getInstance();
        currentMonth = calendar.get(Calendar.MONTH);
        currentDay = calendar.get(Calendar.DAY_OF_MONTH);
        currentYear = calendar.get(Calendar.YEAR);
        
        Date date = new Date(currentYear - 1900, currentMonth, 1);
        calendar.setTime(date);
        firstDay = calendar.get(Calendar.DAY_OF_WEEK) - 1;       
        schedulingCalendar = new SchedulingCalendar(mainFrame, this, null);
        CalendarPanel.add(schedulingCalendar);
        CalendarPanel.setLayout(new GridLayout(1, 1));

    }
    
    public SchedulingPanel getSchedulingPanel(){
        return this;
    }
    
    public int getCalendarPanelWidth(){
        return CalendarPanel.getWidth();
    }
    
    public int getCalendarPanelHeight(){
        return CalendarPanel.getHeight();
    }
    
    public void setDate(Date date){
        calendar.setTime(date);
        YearLabel.setText("" + getCurrentYear());
        MonthLabel.setText(months[getCurrentMonth()]);
        schedulingCalendar.changeMonth();
    }

    public int getFirstDay() {
//        Calendar cal = Calendar.getInstance();
//        cal.setTime(new Date(getCurrentYear(), getCurrentMonth(), 1));
//        return firstDay = cal.get(Calendar.DAY_OF_MONTH);
    return firstDay;
    }

    public int getCurrentMonth() {
        return currentMonth = calendar.get(Calendar.MONTH);
    }

    public void setCurrentMonth(int currentMonth) {
        this.currentMonth = currentMonth;
    }

    public int getCurrentDay() {
        return currentDay = calendar.get(Calendar.DAY_OF_MONTH);
    }

    public void setCurrentDay(int currentDay) {
        this.currentDay = currentDay;
    }

    public int getCurrentYear() {
        return currentYear = calendar.get(Calendar.YEAR);
    }

    public void setCurrentYear(int currentYear) {
        this.currentYear = currentYear;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CurrentUserLabel = new javax.swing.JLabel();
        ClockLabel = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        YearLabel = new javax.swing.JLabel();
        MonthLabel = new javax.swing.JLabel();
        NextMonthButton = new javax.swing.JButton();
        PreviousMonthButton = new javax.swing.JButton();
        CalendarPanel = new javax.swing.JPanel();

        CurrentUserLabel.setText("Welcome: User's Name");

        ClockLabel.setText("jTextField1");
        ClockLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClockLabelActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        YearLabel.setText("jLabel1");

        MonthLabel.setText("jLabel2");

        NextMonthButton.setText("Next Month");
        NextMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextMonthButtonActionPerformed(evt);
            }
        });

        PreviousMonthButton.setText("Previous Month");
        PreviousMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousMonthButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalendarPanelLayout = new javax.swing.GroupLayout(CalendarPanel);
        CalendarPanel.setLayout(CalendarPanelLayout);
        CalendarPanelLayout.setHorizontalGroup(
            CalendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CalendarPanelLayout.setVerticalGroup(
            CalendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PreviousMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 516, Short.MAX_VALUE)
                        .addComponent(NextMonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YearLabel)
                            .addComponent(MonthLabel)
                            .addComponent(CurrentUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CalendarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CurrentUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(YearLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MonthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextMonthButton)
                    .addComponent(PreviousMonthButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClockLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClockLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClockLabelActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        mainFrame.setNewPanel(new MainMenuPanel(mainFrame), Boolean.FALSE, this);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void PreviousMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousMonthButtonActionPerformed
        
        Date date;
        
        if(currentMonth== 0){
            currentMonth = 11;
            currentYear--;
            date = new Date(currentYear - 1900, currentMonth, 1);
        }
        else{
            currentMonth--;
            date = new Date(currentYear - 1900, currentMonth, 1);
        }
                
        calendar.setTime(date);
        firstDay = calendar.get(Calendar.DAY_OF_WEEK)-1;
        schedulingCalendar.changeMonth();
        MonthLabel.setText(months[currentMonth]);
        YearLabel.setText("" + currentYear);
    }//GEN-LAST:event_PreviousMonthButtonActionPerformed

    private void NextMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextMonthButtonActionPerformed
        Date date;
        
        if(currentMonth== 11){
            currentMonth = 0;
            currentYear++;
            date = new Date(currentYear - 1900, currentMonth, 1);
        }
        else{
            currentMonth++;
            date = new Date(currentYear - 1900, currentMonth, 1);
        }
                
        calendar.setTime(date);
        firstDay = calendar.get(Calendar.DAY_OF_WEEK) - 1;
        schedulingCalendar.changeMonth();
        MonthLabel.setText(months[currentMonth]);
        YearLabel.setText("" + currentYear);
    }//GEN-LAST:event_NextMonthButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel CalendarPanel;
    private javax.swing.JTextField ClockLabel;
    private javax.swing.JLabel CurrentUserLabel;
    private javax.swing.JLabel MonthLabel;
    private javax.swing.JButton NextMonthButton;
    private javax.swing.JButton PreviousMonthButton;
    private javax.swing.JLabel YearLabel;
    // End of variables declaration//GEN-END:variables
}
