package possystem;

import possystem.menuitems.MenuItem;
import possystem.menuitems.Topping;

/**
 *
 * @author dakingofcheckerz
 */
public class ToppingPanel extends javax.swing.JPanel {

    private Topping topping;
    private Integer count;
    private int maxQuantity;

    /**
     * Creates new form ToppingPanel
     */
    public ToppingPanel(MenuItem topping) {
        initComponents();

        // Should proabably not do this, but it works in a pinch
        if (!(topping instanceof Topping)) {
            throw new IllegalArgumentException();
        }

        this.topping = (Topping) topping;
        this.count = 0;

        initialize();
    }

    private void initialize() {
        this.ToppingNameLabel.setText(topping.getName());
        this.maxQuantity = topping.getMaxCount();
    }

    public Topping getTopping() {
        return this.topping;
    }

    public int getCount() {
        return this.count;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DecrementButton = new javax.swing.JButton();
        QuantityLabel = new javax.swing.JLabel();
        IncrementButton = new javax.swing.JButton();
        ToppingNameLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        DecrementButton.setText("-");
        DecrementButton.setPreferredSize(new java.awt.Dimension(60, 33));
        DecrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecrementButtonActionPerformed(evt);
            }
        });
        add(DecrementButton, java.awt.BorderLayout.LINE_START);

        QuantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuantityLabel.setText("0");
        QuantityLabel.setPreferredSize(new java.awt.Dimension(22, 15));
        add(QuantityLabel, java.awt.BorderLayout.CENTER);

        IncrementButton.setText("+");
        IncrementButton.setPreferredSize(new java.awt.Dimension(60, 33));
        IncrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncrementButtonActionPerformed(evt);
            }
        });
        add(IncrementButton, java.awt.BorderLayout.LINE_END);

        ToppingNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ToppingNameLabel.setText("Topping Name");
        add(ToppingNameLabel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void DecrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecrementButtonActionPerformed
        if (count > 0) {
            count--;
        }

        updateQuantityLabel();
    }//GEN-LAST:event_DecrementButtonActionPerformed

    private void IncrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncrementButtonActionPerformed
        if (count < maxQuantity || maxQuantity == 0) {
            count++;
        }

        updateQuantityLabel();
    }//GEN-LAST:event_IncrementButtonActionPerformed

    private void updateQuantityLabel() {
        this.QuantityLabel.setText(count.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DecrementButton;
    private javax.swing.JButton IncrementButton;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JLabel ToppingNameLabel;
    // End of variables declaration//GEN-END:variables
}
