/*
 * Here comes the text of your license
 * Each line should be prefixed with  *
 */
package possystem;

import possystem.menuitems.MenuItem;
import possystem.menuitems.Topping;

/**
 *
 * @author dakingofcheckerz
 */
public class ToppingPanel extends javax.swing.JPanel {

    private Topping topping;

    /**
     * Creates new form ToppingPanel
     */
    public ToppingPanel(MenuItem topping) {
        initComponents();

        // Should proabably not do this, but it works in a pinch
        if (!(topping instanceof Topping)) {
            throw new IllegalArgumentException();
        }

        this.topping = (Topping) topping;

        initialize();
    }

    private void initialize() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ToppingNameLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        QuantityLabel = new javax.swing.JLabel();
        IncrementButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        ToppingNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ToppingNameLabel.setText("Topping Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(ToppingNameLabel, gridBagConstraints);

        jButton1.setText("-");
        jButton1.setPreferredSize(new java.awt.Dimension(25, 33));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jButton1, gridBagConstraints);

        QuantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuantityLabel.setText("0");
        QuantityLabel.setPreferredSize(new java.awt.Dimension(22, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(QuantityLabel, gridBagConstraints);

        IncrementButton.setText("+");
        IncrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncrementButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(IncrementButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IncrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncrementButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncrementButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IncrementButton;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JLabel ToppingNameLabel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
